
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//
// <copyright file="Pages.cs" company="ASK-EHS">
//    All copy rights reserved @ASK-EHS.
// </copyright>
//------------------------------------------------------------------------------
namespace MVCProject
{
    /// <summary>
    /// Module Pages
    /// Database table name 'ModulePage'
    /// </summary>
    public static class Pages
    {
        /// <summary>
        /// Landing Pages Module
        /// This code was generated from a template.
        /// </summary>
        public const int Module_General = 1;

        /// <summary>
        /// Class contains Pages ofGeneral Module
        /// This code was generated from a template.
        /// </summary>
        public static class General
        {

            public const int User = 2;

            public const int Designation = 3;

            public const int CommonConfiguartion = 4;

            public const int HWM = 1;

            /// <summary>
            /// Role Level Page 
            /// This code was generated from a template.
            /// </summary>
            public const int RoleLevel = 5;

            /// <summary>
            /// Role Master Page 
            /// This code was generated from a template.
            /// </summary>
            public const int RoleMaster = 6;


        }


    }
}